service: Comparendos_Backend
version: '3.9'

services:
  infractions_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    env_file:
      - .env
    environment:
      - PROXY_READ_TIMEOUT=500s
    ports:
      - "8000:8000"

functions:
  main:
    timeout: 60
    memorySize: 5000
    events:
      - http:
          path: prod
          method: post
    image:
      name: img
